import Head from 'next/head'
import { NextPage } from 'next'
import Hero from '../components/hero'
import Layout from "../components/layout";
const Home:NextPage = () => {
  return (
    <>
      <Head>
        <title>Movie app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./fav.png" />
      </Head>
      <Hero/>
    </>
  )
}
export default Home;
