import React from 'react'
import MovieDetailComp from '../../components/movieDetail';
import Head from 'next/head';
import { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import { DetailRes, MovieApiRes } from '../../services/types';
import { getMovieDetail, getMovies } from '../../services/api';
interface Iprops{
  result:DetailRes
}
const MovieDetail:NextPage<Iprops> = ({result}) => {
  return (
    <>
      <Head children={undefined}>
        <title>Movie app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./fav.png" />
      </Head>
      <MovieDetailComp data={result}/>
    </>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const res:MovieApiRes = await getMovies();
  let movies=res.Search
  let movie_id=movies.map((item)=>{
    return(
      {
        params: {
          movie_id: item.imdbID,
        },
      }
    )
  })
  return {
    paths: movie_id,
    fallback: false, // true or "blocking"
  }
}

export const getStaticProps:GetStaticProps=async(ctx)=>{  
  let {movie_id}=ctx.params
  const res:DetailRes = await getMovieDetail(movie_id);
  let result=null;
  if(res){
    result=res
  }
  return { 
    props: { result } 
  }
}

export default MovieDetail;