import React from 'react'
import Head from 'next/head'
import AllMovies from '../../components/allMovies'
import type { NextPage, GetStaticProps } from 'next'
import { MovieApiRes } from '../../services/types';
import { getMovies } from '../../services/api';

interface Iprops{
  result:MovieApiRes
}
const Allmovies:NextPage<Iprops> = ({result}) => {
  return (
    <>
      <Head children={undefined}>
        <title>Movie app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./fav.png" />
      </Head>
      <AllMovies data={result.Search}/>
    </>
  )
}

export const getStaticProps:GetStaticProps=async()=>{
  const res:MovieApiRes = await getMovies();
  let result=null;
  if(res){
    result=res
  }
  return { 
    props: { result } 
  }
}

export default Allmovies;